FROM ubuntu:20.04

RUN apt-get update \
    && apt-get install software-properties-common -y \
    && apt-get install python3.9 -y \
    && apt-get install python3-pip -y \
    && apt-get install python3.9-distutils -y

RUN python3.9 -m pip install --upgrade setuptools pip distlib

RUN apt-get install git -y \
    && git clone https://github.com/TheMasteredPanda/UK-Parliament-Library.git \
    && python3.9 -m pip install -e UK-Parliament-Library


WORKDIR /TLDR-Bot

COPY src/requierments/requirements-bot.txt .

RUN python3.9 -m pip install -U py-cord --pre
RUN python3.9 -m pip install -r requirements-bot.txt

COPY src/ .

ENV IN_DOCKER Yes

ENTRYPOINT ["sh", "-c", "python3.9 bot.py"]
