- name: install gnupg
  apt:
    name: gnupg

- name: add mongodb key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present

- name: add mongodb source
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
    filename: "mongodb-org-5.0"

- name: install mongodb packages
  apt:
    name: mongodb-org
    state: present
  register: mongodb_installed

- name: wait after mongo install
  pause:
    seconds: 15
  when: mongodb_installed.changed


- name: clone or update tldrbot repo
  git:
    repo: "{{ tldrbot_repo }}"
    dest: /home/tldrbot/TLDR-Bot
    version: master
    force: yes

- name: copy db config
  copy:
    src: env_file_encrypted
    dest: /home/tldrbot/TLDR-Bot/.env

- name: deploy mongodb docker container
  docker_compose:
    project_src: /home/tldrbot/TLDR-Bot
    files: docker-compose-deploy-database.yml
    pull: yes

- name: create target directory
  file: 
    path: /home/tldrbot/mongodb
    state: directory

- name: copy over backup and restore scripts
  template:
    src: "{{ item }}"
    dest: "/home/tldrbot/mongodb/{{ item }}"
    mode: "+x"
  with_items:
    - backup.sh
    - restore.sh

- name: set up cron task for database backup
  cron:
    name: "mongodb"
    minute: "0"
    hour: "2"
    job: "/home/tldrbot/mongodb/backup.sh >/dev/null 2>&1"
