- name: install docker and docker-compose
  apt:
    name:
      - docker
      - docker-compose
- name: Pip install Requests
  pip:
    name: 
      - requests 
      - docker 

- name: create tldr-net network
  docker_network:
    name: "tldr-net"
    state: present
