name: auto-build-push

on:
  push:
    branches:
      - 'master'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bot
        id: docker_build_bot
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: themasteredpanda/tldr-bot:latest
          context: .
          file: ./Dockerfile-bot
      - name: Build and push api
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: themasteredpanda/tldr-api:latest
          context: .
          file: ./Dockerfile-api

  run-playbook:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infra.yaml
          directory: ./ansible
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          requirements: requirements.yml
